# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 13:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='moves',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=42),
        ),
    ]
